// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlWrvh9wE91Ga55oqI9nedOgjcHYjbrY',
    appId: '1:394057566347:web:c0f399316d5dfc9c44ac8e',
    messagingSenderId: '394057566347',
    projectId: 'classroom-b8abe',
    authDomain: 'classroom-b8abe.firebaseapp.com',
    storageBucket: 'classroom-b8abe.appspot.com',
    measurementId: 'G-4B2BWNJSGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkOqbz-QvaHGTElOKmvpwP_nleLvVxXw',
    appId: '1:394057566347:android:a0af3a697fc6d71a44ac8e',
    messagingSenderId: '394057566347',
    projectId: 'classroom-b8abe',
    storageBucket: 'classroom-b8abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy5Zz3eku0nkIaGdhzk4wFl1F-m4lkUl4',
    appId: '1:394057566347:ios:46de451ac8c276d244ac8e',
    messagingSenderId: '394057566347',
    projectId: 'classroom-b8abe',
    storageBucket: 'classroom-b8abe.appspot.com',
    androidClientId: '394057566347-vh06pv2d7bhkn1gd1a6rfkeij3n4rp27.apps.googleusercontent.com',
    iosClientId: '394057566347-a07kq956jimij70gob26bsd4u7r5v1n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy5Zz3eku0nkIaGdhzk4wFl1F-m4lkUl4',
    appId: '1:394057566347:ios:46de451ac8c276d244ac8e',
    messagingSenderId: '394057566347',
    projectId: 'classroom-b8abe',
    storageBucket: 'classroom-b8abe.appspot.com',
    androidClientId: '394057566347-vh06pv2d7bhkn1gd1a6rfkeij3n4rp27.apps.googleusercontent.com',
    iosClientId: '394057566347-a07kq956jimij70gob26bsd4u7r5v1n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
